import api from '../lib/api';

const reportService = {
  /**
   * Downloads Sales Report PDF matching filter criteria.
   * @param {object} filters - startDate, endDate, saleType, billingType, party, search
   * @returns {Promise<Blob>}
   */
  downloadSalesReport: async (filters) => {
    const res = await api.get('/reports/sell/pdf', {
      params: filters,
      responseType: 'blob',
    });
    return res.data;
  },

  /**
   * Downloads Purchase Report PDF matching filter criteria.
   * @param {object} filters - startDate, endDate, purchaseType, billingType, party, search
   * @returns {Promise<Blob>}
   */
  downloadPurchaseReport: async (filters) => {
    const res = await api.get('/reports/purchase/pdf', {
      params: filters,
      responseType: 'blob',
    });
    return res.data;
  },

  /**
   * Fetches JSON data for Balance Sheet statement.
   * @param {string} date - The snapshot date (YYYY-MM-DD)
   * @returns {Promise<object>}
   */
  fetchBalanceSheet: async (date) => {
    const res = await api.get('/reports/balance-sheet', {
      params: { date, format: 'json' },
    });
    return res.data;
  },

  /**
   * Downloads Balance Sheet PDF for statement date.
   * @param {string} date - The snapshot date (YYYY-MM-DD)
   * @returns {Promise<Blob>}
   */
  downloadBalanceSheetPdf: async (date) => {
    const res = await api.get('/reports/balance-sheet', {
      params: { date, format: 'pdf' },
      responseType: 'blob',
    });
    return res.data;
  },

  /**
   * Downloads Payment In Report PDF.
   * @param {object} filters - party, paymentType, isAutoGenerated, startDate, endDate, search
   * @returns {Promise<Blob>}
   */
  downloadPaymentInReport: async (filters) => {
    const res = await api.get('/reports/payment-in/pdf', {
      params: filters,
      responseType: 'blob',
    });
    return res.data;
  },

  /**
   * Downloads Payment Out Report PDF.
   * @param {object} filters - party, paymentType, isAutoGenerated, startDate, endDate, search
   * @returns {Promise<Blob>}
   */
  downloadPaymentOutReport: async (filters) => {
    const res = await api.get('/reports/payment-out/pdf', {
      params: filters,
      responseType: 'blob',
    });
    return res.data;
  },

  /**
   * Downloads Expense Report PDF.
   * @param {object} filters - party, category, paymentType, gstEnabled, startDate, endDate, search
   * @returns {Promise<Blob>}
   */
  downloadExpenseReport: async (filters) => {
    const res = await api.get('/reports/expense/pdf', {
      params: filters,
      responseType: 'blob',
    });
    return res.data;
  },

  /**
   * Fetches JSON data for Party Sale-Purchase report.
   * @param {object} filters - startDate, endDate, search
   * @returns {Promise<object>}
   */
  fetchPartySalePurchaseReport: async (filters) => {
    const res = await api.get('/party/reports/sale-purchase', {
      params: filters,
    });
    return res.data;
  },

  /**
   * Fetches JSON data for Itemwise Profit-Loss report.
   * @param {object} filters - startDate, endDate, itemsHavingSale
   * @returns {Promise<object>}
   */
  fetchItemwiseProfitLossReport: async (filters) => {
    const res = await api.get('/reports/itemwise-profit-loss', {
      params: filters,
    });
    return res.data;
  },

  /**
   * Downloads GSTR-1 Report in JSON or CSV format matching query options.
   * @param {object} filters - month, year, startDate, endDate, format
   * @returns {Promise<Blob>}
   */
  downloadGstr1Report: async (filters) => {
    const res = await api.get('/reports/gstr-1', {
      params: filters,
      responseType: 'blob',
    });
    return res.data;
  },

  /**
   * Downloads GSTR-3B Report matching query options.
   * @param {object} filters - month, year, startDate, endDate, format
   * @returns {Promise<Blob>}
   */
  downloadGstr3bReport: async (filters) => {
    const res = await api.get('/reports/gstr-3b', {
      params: filters,
      responseType: 'blob',
    });
    return res.data;
  },

  /**
   * Fetches JSON data for GSTR-3B report.
   * @param {object} filters - month, year, startDate, endDate
   * @returns {Promise<object>}
   */
  fetchGstr3bReport: async (filters) => {
    const res = await api.get('/reports/gstr-3b', {
      params: { ...filters, format: 'json' },
    });
    return res.data;
  },

  /**
   * Downloads Procurement Report PDF.
   * @param {object} filters - farmer, procurementCenter, startDate, endDate, search
   * @returns {Promise<Blob>}
   */
  downloadProcurementReport: async (filters) => {
    const res = await api.get('/reports/procurement/pdf', {
      params: filters,
      responseType: 'blob',
    });
    return res.data;
  },
};

export default reportService;
