import React from "react";
import { Eye, Download, Pencil, Trash2 } from "lucide-react";
import { EmptyState } from "../utils/purchaseHelpers";

export default function PaymentsOutListTab({
  displayedPayments = [],
  getPartyName,
  formatDate,
  isReadOnly,
  handleOpenDetailModal,
  handleDownloadPaymentOutReceipt,
  setEditPaymentRecord,
  setPaymentModalOpen,
  setDeleteConfirmId,
  setDeleteConfirmType,
}) {
  return (
    <table className="w-full border-collapse text-left text-sm">
      <thead className="bg-gray-50 border-b border-gray-100 text-xs text-gray-600 uppercase font-semibold">
        <tr>
          <th className="px-6 py-3">Receipt No</th>
          <th className="px-6 py-3">Date</th>
          <th className="px-6 py-3">Supplier/Party</th>
          <th className="px-6 py-3">Paid Breakdowns</th>
          <th className="px-6 py-3 text-right">Total Amount</th>
          <th className="px-6 py-3 text-right">Actions</th>
        </tr>
      </thead>
      <tbody className="divide-y divide-gray-100">
        {displayedPayments.length === 0 ? (
          <tr className="hover:bg-transparent">
            <td colSpan={6} className="px-6 py-16 text-center">
              <EmptyState
                title="No Payments Out Found"
                description="Track outgoing transactions, checkouts, and deposits made to your product suppliers."
              />
            </td>
          </tr>
        ) : (
          displayedPayments.map((item) => (
            <tr key={item._id} className="hover:bg-gray-50 transition">
              <td className="px-6 py-2.5">
                <div className="flex flex-col">
                  <span className="font-bold text-gray-900">
                    {item.receiptNo || item._id.substring(0, 8).toUpperCase()}
                  </span>
                  {item.isAutoGenerated ? (
                    <span className="inline-flex items-center w-fit mt-1 px-1.5 py-0.5 rounded text-[10px] font-bold bg-blue-50 text-blue-700 border border-blue-100">
                      Auto-Generated
                    </span>
                  ) : (
                    <span className="inline-flex items-center w-fit mt-1 px-1.5 py-0.5 rounded text-[10px] font-bold bg-gray-100 text-gray-700 border border-gray-250">
                      Manual
                    </span>
                  )}
                </div>
              </td>
              <td className="px-6 py-2.5 text-gray-505 whitespace-nowrap">{formatDate(item.date)}</td>
              <td className="px-6 py-2.5 font-semibold text-gray-805 truncate max-w-[220px]" title={getPartyName(item) || "Unknown Supplier"}>
                {getPartyName(item) || "Unknown Supplier"}
              </td>
              <td className="px-6 py-2.5">
                <div className="flex flex-wrap gap-1">
                  {item.payments?.map((py, idx) => (
                    <span key={idx} className="inline-block px-2 py-0.5 rounded bg-gray-100 text-gray-700 text-xs uppercase font-medium">
                      {py.paymentType}: ₹{py.amount}
                    </span>
                  ))}
                </div>
              </td>
              <td className="px-6 py-2.5 text-right font-extrabold text-red-650">
                ₹{(item.paidAmount || 0).toLocaleString("en-IN")}
              </td>
              <td className="px-6 py-2.5 text-right">
                <div className="flex justify-end gap-2">
                  <button
                    onClick={() => handleOpenDetailModal(item, "payment")}
                    className="p-2 text-gray-600 hover:text-brand-700 hover:bg-brand-50 rounded-lg transition cursor-pointer"
                    title="View Details"
                  >
                    <Eye className="w-4 h-4" />
                  </button>
                  <button
                    onClick={() => handleDownloadPaymentOutReceipt(item._id)}
                    className="p-2 text-gray-600 hover:text-blue-700 hover:bg-blue-50 rounded-lg transition cursor-pointer"
                    title="Download Payment Receipt PDF"
                  >
                    <Download className="w-4 h-4" />
                  </button>
                  {!isReadOnly && (
                    <>
                      {item.isAutoGenerated ? (
                        <span
                          className="p-2 text-gray-400 cursor-not-allowed inline-block"
                          title="Auto-generated payments cannot be edited directly. Edit the linked bill instead."
                        >
                          <Pencil className="w-4 h-4 opacity-40" />
                        </span>
                      ) : (
                        <button
                          onClick={() => {
                            setEditPaymentRecord(item);
                            setPaymentModalOpen(true);
                          }}
                          className="p-2 text-gray-600 hover:text-amber-700 hover:bg-amber-50 rounded-lg transition cursor-pointer"
                          title="Edit Payment"
                        >
                          <Pencil className="w-4 h-4" />
                        </button>
                      )}
                      {item.isAutoGenerated ? (
                        <span
                          className="p-2 text-gray-400 cursor-not-allowed inline-block"
                          title="Auto-generated payments cannot be deleted directly. Delete/update the linked bill instead."
                        >
                          <Trash2 className="w-4 h-4 opacity-40" />
                        </span>
                      ) : (
                        <button
                          onClick={() => {
                            setDeleteConfirmId(item._id);
                            setDeleteConfirmType("payment");
                          }}
                          className="p-2 text-gray-600 hover:text-red-700 hover:bg-red-50 rounded-lg transition cursor-pointer"
                          title="Delete Record"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      )}
                    </>
                  )}
                </div>
              </td>
            </tr>
          ))
        )}
      </tbody>
    </table>
  );
}
